// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTarget(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTarget'](arg1, arg2, arg3);
}

export function AuthorizeTarget(arg1) {
  return window['go']['main']['App']['AuthorizeTarget'](arg1);
}

export function ExportReport(arg1) {
  return window['go']['main']['App']['ExportReport'](arg1);
}

export function GetDiff(arg1) {
  return window['go']['main']['App']['GetDiff'](arg1);
}

export function GetLatestSnapshot(arg1) {
  return window['go']['main']['App']['GetLatestSnapshot'](arg1);
}

export function GetScopeRoots() {
  return window['go']['main']['App']['GetScopeRoots']();
}

export function GetTelegramStatus() {
  return window['go']['main']['App']['GetTelegramStatus']();
}

export function IsMonitoring() {
  return window['go']['main']['App']['IsMonitoring']();
}

export function ListTargets() {
  return window['go']['main']['App']['ListTargets']();
}

export function StartMonitoring() {
  return window['go']['main']['App']['StartMonitoring']();
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}
