// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartScan(arg1:string):Promise<void>;

export function StopScan():Promise<void>;
