// Package report turns RadarX data into human-readable markdown: an asset
// inventory for a target and a change log, formatted so findings can be dropped
// straight into notes or a bug bounty submission.
package report

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/americooo/radarx/internal/model"
)

// Inventory renders a target's latest snapshot as a markdown asset inventory,
// grouped by kind. This is the "what does the attack surface look like right
// now" view.
func Inventory(t model.Target, snap model.Snapshot) string {
	var b strings.Builder

	name := t.Label
	if name == "" {
		name = t.Root
	}
	fmt.Fprintf(&b, "# Attack Surface — %s\n\n", name)
	fmt.Fprintf(&b, "- **Root:** `%s`\n", t.Root)
	fmt.Fprintf(&b, "- **Scanned:** %s\n", snap.TakenAt.Format(time.RFC3339))
	fmt.Fprintf(&b, "- **Total assets:** %d\n\n", len(snap.Assets))

	byKind := map[model.AssetKind][]model.Asset{}
	for _, a := range snap.Assets {
		byKind[a.Kind] = append(byKind[a.Kind], a)
	}

	writeSubdomains(&b, byKind[model.KindSubdomain])
	writeEndpoints(&b, byKind[model.KindEndpoint])
	writePorts(&b, byKind[model.KindPort])
	writeCerts(&b, byKind[model.KindCert])

	b.WriteString("\n---\n_Generated by RadarX. Only assets within authorized scope._\n")
	return b.String()
}

// ChangeLog renders a diff result as a markdown change log — useful to paste
// into a report when a newly discovered asset leads to a finding.
func ChangeLog(d model.DiffResult) string {
	var b strings.Builder
	fmt.Fprintf(&b, "## Changes — %s (%s)\n\n", d.Root, d.At.Format(time.RFC3339))
	if !d.HasSignal() {
		b.WriteString("_No changes._\n")
		return b.String()
	}
	fmt.Fprintf(&b, "**%d new**, %d total changes.\n\n", d.NewCount(), len(d.Changes))
	b.WriteString("| Change | Kind | Asset | Detail |\n|---|---|---|---|\n")
	for _, c := range d.Changes {
		detail := ""
		switch c.Type {
		case model.ChangeModified:
			detail = strings.Join(c.Fields, ", ")
		case model.ChangeNew:
			if c.After != nil && c.After.StatusCode != 0 {
				detail = fmt.Sprintf("HTTP %d", c.After.StatusCode)
			}
		}
		fmt.Fprintf(&b, "| %s | %s | `%s` | %s |\n",
			badge(c.Type), c.Kind, c.Key, detail)
	}
	return b.String()
}

func badge(t model.ChangeType) string {
	switch t {
	case model.ChangeNew:
		return "🟢 NEW"
	case model.ChangeModified:
		return "🟡 CHANGED"
	case model.ChangeRemoved:
		return "🔴 REMOVED"
	default:
		return string(t)
	}
}

func writeSubdomains(b *strings.Builder, assets []model.Asset) {
	if len(assets) == 0 {
		return
	}
	sort.Slice(assets, func(i, j int) bool { return assets[i].Host < assets[j].Host })
	fmt.Fprintf(b, "## Subdomains (%d)\n\n", len(assets))
	for _, a := range assets {
		ip := ""
		if len(a.IP) > 0 {
			ip = " → " + strings.Join(a.IP, ", ")
		}
		fmt.Fprintf(b, "- `%s`%s\n", a.Host, ip)
	}
	b.WriteString("\n")
}

func writeEndpoints(b *strings.Builder, assets []model.Asset) {
	if len(assets) == 0 {
		return
	}
	sort.Slice(assets, func(i, j int) bool { return assets[i].Key < assets[j].Key })
	fmt.Fprintf(b, "## HTTP Endpoints (%d)\n\n", len(assets))
	b.WriteString("| URL | Status | Title | Server |\n|---|---|---|---|\n")
	for _, a := range assets {
		fmt.Fprintf(b, "| %s | %d | %s | %s |\n",
			a.Key, a.StatusCode, mdEscape(a.Title), mdEscape(a.Server))
	}
	b.WriteString("\n")
}

func writePorts(b *strings.Builder, assets []model.Asset) {
	if len(assets) == 0 {
		return
	}
	byHost := map[string][]int{}
	for _, a := range assets {
		byHost[a.Host] = append(byHost[a.Host], a.Port)
	}
	fmt.Fprintf(b, "## Open Ports\n\n")
	hosts := make([]string, 0, len(byHost))
	for h := range byHost {
		hosts = append(hosts, h)
	}
	sort.Strings(hosts)
	for _, h := range hosts {
		ports := byHost[h]
		sort.Ints(ports)
		fmt.Fprintf(b, "- `%s`: %s\n", h, joinInts(ports))
	}
	b.WriteString("\n")
}

func writeCerts(b *strings.Builder, assets []model.Asset) {
	if len(assets) == 0 {
		return
	}
	sort.Slice(assets, func(i, j int) bool { return assets[i].Host < assets[j].Host })
	fmt.Fprintf(b, "## TLS Certificates (%d)\n\n", len(assets))
	b.WriteString("| Host | Common Name | Expires |\n|---|---|---|\n")
	for _, a := range assets {
		fmt.Fprintf(b, "| `%s` | %s | %s |\n", a.Host, mdEscape(a.CertCN), a.CertExpiry)
	}
	b.WriteString("\n")
}

func joinInts(ns []int) string {
	parts := make([]string, len(ns))
	for i, n := range ns {
		parts[i] = fmt.Sprintf("%d", n)
	}
	return strings.Join(parts, ", ")
}

func mdEscape(s string) string {
	return strings.NewReplacer("|", "\\|", "\n", " ").Replace(s)
}
